const BLOG_CACHE_PATTERN = "BLOG";
const EVENTS_CACHE_PATTERN = "EVENTS";
const GAIATAS_CACHE_PATTERN = "GAIATAS";
const SETTINGS_CACHE_PATTERN = "SETTINGS";

module.exports = {
  BLOG_CACHE_PATTERN,
  EVENTS_CACHE_PATTERN,
  GAIATAS_CACHE_PATTERN,
  SETTINGS_CACHE_PATTERN,
};
